### PR TITLE
Update Xcode 10.3 UUID

### PR DESCRIPTION
**Pull request by matvdg**

### CODE REVIEW

**Comment by designatednerd** [comment]
@matvdg Can you please sign the agreement? Otherwise I'll need to close this PR and open a different one.

**Comment by designatednerd** [comment]
OK, I need to actually get this shipped so I'll be doing this as a separate PR.

**Comment by matvdg** [comment]
Oh, I'm really sorry about that @designatednerd, I took long holidays this year :( Thanks anyway

**Comment by designatednerd** [comment]
No problem! In the future if you plan to submit something, you can sign the CLA now and then not have to worry about it at that point.

**Pull request closed without merging**
